# RuboCopの全体的な設定
AllCops:
  # 対象とするRubyのバージョン
  TargetRubyVersion: 3.3
  # 対象外とするファイルやディレクトリ
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/initializers/**/*'
    - 'lib/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'spec/**/*'

# 特定のCopの設定
Metrics/LineLength:
  # 1行の最大文字数を80から100に変更
  Max: 100

Style/FrozenStringLiteralComment:
  # frozen_string_literalマジックコメントを要求するルールを無効にする
  Enabled: false

Documentation:
  # すべてのクラスとモジュールの先頭にドキュメントのコメントを要求するルールを無効にする
  Enabled: false