# RuboCopの全体的な設定
AllCops:
  # 対象とするRubyのバージョン
  TargetRubyVersion: 3.3
  # 対象外とするファイルやディレクトリ
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'lib/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'spec/**/*'
    - 'Gemfile'

# 特定のCopの設定
Metrics/LineLength:
  # 1行の最大文字数を80から120に変更
  Max: 120

Metrics/MethodLength:
  # 1つのメソッドの最大行数を10から12に変更
  Max: 12

Style/FrozenStringLiteralComment:
  # frozen_string_literalマジックコメントを要求するルールを無効にする
  Enabled: false

Documentation:
  # すべてのクラスとモジュールの先頭にドキュメントのコメントを要求するルールを無効にする
  Enabled: false

Naming/AccessorMethodName:
  # アクセサメソッド接頭語に関するルールを無効にする
  Enabled: false